export enum UserActionsType{
  FETCH_USERS = 'FETCH_USERS',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR = 'FETCH_USERS_ERROR',
  SORT_USERS = "SORT_USERS",
  CHANGE_USERS_FILTER_TYPE= "CHANGE_USERS_FILTER_TYPE",
  CHANGE_USERS_FILTER_DIRRECTION = "CHANGE_USERS_FILTER_DIRRECTION"
} 
export enum ToDoActionsType{
  FETCH_TODO = 'FETCH_TODO',
  FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS',
  FETCH_TODO_COMPLETED_SUCCESS = 'FETCH_TODO_COMPLETED_SUCCESS',
  FETCH_TODO_COMPLETED = 'FETCH_TODO_COMPLETED',
  FETCH_TODO_UNCOMPLETED = 'FETCH_TODO_UNCOMPLETED',
  FETCH_TODO_UNCOMPLETED_SUCCESS = 'FETCH_TODO_UNCOMPLETED_SUCCESS',
  FETCH_TODO_ERROR = 'FETCH_TODO_ERROR',
  CHANGE_TODO_IS_WALL = 'CHANGE_TODO_IS_WALL',
  CHANGE_TODO_IS_TASK = 'CHANGE_TODO_IS_TASK',
  UPDATE_TODO_LIST = 'UPDATE_TODO_LIST',
  UPDATE_TODO_COMPLETED_LIST = 'UPDATE_TODO_COMPLETED_LIST',
  UPDATE_TODO_UNCOMPLETED_LIST = 'UPDATE_TODO_UNCOMPLETED_LIST'
} 